conditioning:
  method: multips
  params:
    scale: 1.0

data:
  name: video
  root: ./data/dps_cacti/

measurement:
  subframes: 4
  multi: true
  operator_0:
    name: coded_inverse
    subframes: 4
    code_type: simple

  operator_1:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 2
  
  noise: 
    name: gaussian
    sigma: 0.00
