conditioning:
  method: ps
  params:
    scale: 1.0

data:
  name: video
  root: ./data/dps_cacti/

measurement:
  subframes: 4
  operator:
    name: coded_inverse
    subframes: 4
    code_type: simple
  
  noise: 
    name: gaussian
    sigma: 0.00
